FROM node:10

ARG API_URL
ARG WEB_URL
ARG STRIPE_KEY

ENV API_URL=$API_URL
ENV WEB_URL=$WEB_URL
ENV STRIPE_KEY=$STRIPE_KEY

# Setting working directory. All the path will be relative to WORKDIR
WORKDIR /usr/src/app

# Installing dependencies
COPY package*.json ./
RUN npm install

# Copying source files
COPY . .

# Building app
RUN npm run build

EXPOSE 3000

# Running the app
CMD [ "npm", "start" ]