defaults.url=https://sentry.io/
defaults.org=mangomoe
defaults.project=trabajosremotos-client
cli.executable=../../.npm/_npx/16163/lib/node_modules/@sentry/wizard/node_modules/@sentry/cli/bin/sentry-cli
